build:
  image: ensime/ensime:v1.x-cache
  pull: true
  commands:
    - if [ -n "$CI_PULL_REQUEST" ] ; then
        echo "Incoming pull request from https://github.com/$CI_REPO/pull/$CI_PULL_REQUEST";
        author=$(curl -s "https://api.github.com/repos/$CI_REPO/pulls/$CI_PULL_REQUEST" | jq -r ".user.login");
        if [ $? -ne 0 ] ; then exit 1; fi;
      fi

matrix:
  SCALA_VERSION:
    - 2.11.8
